### ISSUE TITLE
BUG: grind: AttributeError: 'Namespace' object has no attribute 'include'

### ISSUE THREAD

**Issue by westurner** [rsalmaso/grin3#5]
```python
$ grind
Traceback (most recent call last):
  File "/home/user/.local/bin/grind", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/grin3/lib64/python3.8/site-packages/grin/grind.py", line 187, in main
    fr = get_recognizer(args)
  File "/home/user/.local/pipx/venvs/grin3/lib64/python3.8/site-packages/grin/recognizer.py", line 328, in get_recognizer
    include=args.include,
AttributeError: 'Namespace' object has no attribute 'include'

```

```
$ python -V
Python 3.8.6

$ python -m pip install --user pipx; pipx install grin3
```

Looks like there's no `args.include` here:

https://github.com/rsalmaso/grin3/blob/25b753112e51bb45c26c4c651d5239e1917c69ef/grin/recognizer.py#L328

When I changed this to 

```python
include=getattr(args, 'include', None),
```

It seemed to run fine.

**Comment by rsalmaso** [comment]
Fixed in https://github.com/rsalmaso/grin3/releases/tag/2.2.1

**Comment by westurner** [comment]
Thx
